version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: storeMonitoring
      MYSQL_HOST: localhost
    ports:
      - 3307:3306